name: Validate Markdown

on:
  push:
    branches:
      - main
  
  pull_request:
    paths:
      - 'docs/**'

jobs:
  markdown-lint:
    name: Markdown Lint CLI
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: nosborn/github-action-markdown-cli@v3.4.0
        with:
          files: 'docs'
